import random

target = random.randint(1,50)  #random number generated by the computer
chances = 1
print("-----GAME START-----")

while (chances<=3):

    user_number = input(f" Guess The Number between 1-50 or Quit, This is your {chances} chance:")
    if user_number == "Quit":
        print(f" You are choosing to Quit. \n The random number was  : {target} \n THANK YOU FOR PLAYING")
        break

    user_number = int(user_number)
    if user_number == target:
        print("You Won: You have successfully guessed the number")
        break
    elif user_number < target:
        print("No, Your number is small. TRY AGAIN!")
    else:
        print("No, Your number is big. TRY AGAIN!")

    chances+=1

if(chances > 3):
    print("You Lost")
    print(" You have used all your chances :( ")

print("-----GAME OVER----")








